Features/text styled components
code-mentoring/learn pull request #226
Opened 2020-06-16 14:50 UTC by YagoMackay

**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

## Fixed issues 
- Fixes #221

## Changes
-  All <p> <h1> <h2> <h3> and <h4> elements are styled with base style or Styled Components.

## PR Checklist
- [ ] Does your PR contain relevant tests that pass?
- [ ] Is your code linted? `yarn lint` or `yarn lint:fix`
- [ ] Does your code build correctly in ALL projects? `yarn build`

2020-06-23 00:43 UTC, tristanMatthias requested changes
Hey @YagoMackay, thanks for the thoroughness! As for many of the styled component PRs coming through, just some changes around using the theme variables instead of hardcoding.
Cheers dude!

2020-06-23 00:43 UTC, tristanMatthias commented on packages/client/src/components/ProgressWidget/ProgressPath.tsx
> +letter-spacing: 0.1em;
Can we use theme values for all this? It feels quite verbose haha

2020-06-23 00:43 UTC, tristanMatthias commented on packages/client/src/pages/Login/Login.page.tsx
> +font-size: .875rem;
Theme values here too please 🙏

2020-06-23 00:43 UTC, tristanMatthias commented on packages/client/src/pages/Onboarding/OnboardingStep.tsx
> +margin-bottom: 0.75rem;
And here for the margins

2020-06-23 00:43 UTC, tristanMatthias commented on packages/ui/css/base.ts
> +  }
We should probably not do any global classes like this as we're moving away from that style of dev. Mind if we turn this into a component instead?

2020-06-28 15:52 UTC, YagoMackay commented
Thanks for everything @tristanMatthias ! I'll make sure to switch them to theme variables.

2020-06-30 03:37 UTC, tristanMatthias commented
Hey @YagoMackay! I used this PR in #239 as a base. Thanks for this! Made it much easier :)

2020-06-30 03:37 UTC, closed without merging